### ISSUE TITLE
Question about half point byes.

### ISSUE THREAD

**Issue by jbfsoftware** [BieremaBoyzProgramming/bbpPairings#1]
Hello
I'm JP and I am the programmer of the pairings program Sevilla (www.jbfsoftware.com).
I am interested in including a good WM based pairings engine into my software, and would like to consider including bbpPairings (if you don't mind). 
I ran into one issue so far. The .trf input file gives an error message for players being absent with a half point bye in the round to pair. This is because the half point was already included in the score total of the player. bbpPairings seems not to like it, and when I corrected the scores the file was accepted.
However, also the test file of JaVaFo http://www.rrweb.org/javafo/aum/TRFXSample2.txt adds the half point already. As you are trying to be as compatible as possible to JaVaFo, would/could you consider to change this? Otherwise, maybe you could exclude the total point check for players who are not to be paired anyway?
No doubt the correct number of points may be subject of discussion. The original .trf definition for reporting is about completed tournaments, and .trf usage for pairing is beyond the original idea of the .trf. 
B.t.w. I commented the break on line 630 of trf.cpp
              if (matchIndex >= tournament.playedRounds)
              {
//                next line removed by #jph
//                break;
              }
and then my files were accepted. Would this be a working alternative and/or a recommended one?
Best regards,
JP

**Comment by jbierema** [comment]
Hello, JP.

Thank you for your note. We appreciate your interest in BBP Pairings. In version 2.2.0 (released today), input files are accepted whether the scores include or do not include byes in the upcoming round.

We hope this resolves your concern. If you have further difficulties, please do not hesitate to post them.

**Comment by jbfsoftware** [comment]
Re: [BieremaBoyzProgramming/bbpPairings] Question about half point byes. (#1)


Hello Jeremy,

I like the BBP Pairings engine very much. It is OK if I pack the .exe with the installer of the next release of Sevilla? Of course the engine will be credited to you.

Best regards, JP.


Monday, February 6, 2017, 1:55:32 AM, BieremaBoyzProgramming/bbpPairings wrote:





Hello, JP.
Thank you for your note. We appreciate your interest in BBP Pairings. In version 2.2.0 (released today), input files are accepted whether the scores include or do not include byes in the upcoming round.
We hope this resolves your concern. If you have further difficulties, please do not hesitate to post them.

**Comment by jbierema** [comment]
BBP Pairings is available under the GPL. You are free (and encouraged) to include BBP Pairings with your program, as long as you comply with the license requirements, such as including the copyright and license details and making the source code of BBP Pairings available. Also, please be aware that the Windows distribution is statically linked against the Mingw-w64 runtime and contains additional copyright notices and licensing terms.

**Comment by jbfsoftware** [comment]
Re: [BieremaBoyzProgramming/bbpPairings] Question about half point byes. (#1)


Thanks very much. I will include it.
Greetings JP

Monday, April 10, 2017, 1:47:25 AM, BieremaBoyzProgramming/bbpPairings wrote:





BBP Pairings is available under the GPL. You are free (and encouraged) to include BBP Pairings with your program, as long as you comply with the license requirements, such as including the copyright and license details and making the source code of BBP Pairings available. Also, please be aware that the Windows distribution is statically linked against the Mingw-w64 runtime and contains additional copyright notices and licensing terms.
