### ISSUE TITLE
Error when compiling

### ISSUE THREAD

**Issue by bggolding** [BieremaBoyzProgramming/bbpPairings#14]
When I try to compile bbpPairings, I'm getting an error:
```
src/swisssystems/burstein.cpp: In function 'swisssystems::burstein::{anonymous}::points_product swisssystems::burstein::{anonymous}::calculateSonnebornBerger(const tournament::Player&, const tournament::Tournament&, const std::vector<utility::uinttypes::uint<2> >&)':
src/swisssystems/burstein.cpp:215:17: error: ambiguous overload for 'operator*' (operand types are 'swisssystems::burstein::{anonymous}::points_product' {aka 'utility::uinttypes::uint<3>'} and 'const swisssystems::burstein::{anonymous}::adjusted_score' {aka 'const utility::uinttypes::uint<2>'})
  214 |               points_product{ tournament.getPoints(player, match) }
      |               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |               |
      |               uint<3>
  215 |                 * virtualScore;
      |                 ^ ~~~~~~~~~~~~
      |                   |
      |                   uint<2>
```

I'm using g++ (Alpine 12.2.1_git20220924-r4) 12.2.1 20220924.

There seems to be a discrepancy between `pointProductSize` and `adjustedScoreSize` which makes the types of the uint generics differ so the operands of the multiply have different types. I'm not sure how to correct that.

**Comment by anmcn** [comment]
Note that this issue with bbpPairings v5.0.0 only appears when compiled with g++ 12. With g++ 11, it compiles successfully and without any warnings. I believe g++ 12 is flagging an error in the code that was previously overlooked.

If you have docker, you should be able to replicate via:
```
$ docker run -it --rm  gcc:12 
root@abe6fddfbfdc:/# wget https://github.com/BieremaBoyzProgramming/bbpPairings/archive/master.zip
root@abe6fddfbfdc:/# unzip master.zip
root@abe6fddfbfdc:/# cd bbpPairings-master/
root@abe6fddfbfdc:/bbpPairings-master# make
```
vs:
```
$ docker run -it --rm  gcc:11
...
```

**Comment by jbierema** [comment]
Thanks, @bggolding and @anmcn! I believe I have found a fix for this but need to verify some changes in output I am seeing. I am hoping to be able to release the fix within the next week.

**Comment by jbierema** [comment]
Thanks again! It seems that the build failure was GCC 12's way of preventing a code interpretation issue that was causing pairings in the Burstein system to be all messed up (#15). So this report was especially valuable.

**Comment by anmcn** [comment]
Thanks - can confirm, this fixes our issue.
