### ISSUE TITLE
Handle absent players

### ISSUE THREAD

**Issue by aChwalek** [BieremaBoyzProgramming/bbpPairings#20]
Hello,

I can't manage to specify absent players to bbpPairings in order to exclude them from next round pairing.

I found the XXZ parameter in the  [JaVaFo documentation](http://www.rrweb.org/javafo/aum/JaVaFo2_AUM.htm#_Toc524760821), but it does not seem to be handled.
I've also tried to add 0000 - Z in the column of the next round, but it's ignored too.

Am I missing something ?

Please find the sample I use to reproduce the issue : [TRF(x) sample](http://www.rrweb.org/javafo/aum/TRFXSample2.txt)
```
./bbpPairings.exe  --dutch sample.trf -p
```

Players 23, 28 and 43 should be excluded from pairings, but they're not.

Many thank for your work on this project.

**Comment by jbierema** [comment]
@aChwalek I tried this out, and it seems to be working for me, although I think it&rsquo;s Player&nbsp;22 who should be excluded, not Player&nbsp;23. I&rsquo;m including my output below. Let me know if you&rsquo;re getting something different, and we can investigate.
```
25
1 2
3 4
5 6
7 13
11 21
23 12
19 16
17 52
35 18
8 24
9 26
37 10
14 29
45 15
46 20
27 38
34 30
39 31
41 32
42 33
44 48
25 49
40 50
51 36
47 0
```

**Comment by fnogatz** [comment]
Thanks for spotting this, @luhhujbb. I just fixed it in the branch of PR #12.

**Comment by aChwalek** [comment]
Indeed, it was introduced by #12. Thanks for your response.

**Comment by C1977** [comment]
Sorry I have the same problem with the current exe-File (I can't compile myself).
BBP Pairings (https:\/\/github.com\/BieremaBoyzProgramming\/bbpPairings) - v5.0.1 (Built Feb 25 2023 21:22:56)

Example TRF:

012 vregr
XXR 5
XXC black1 rank
XXZ 2
001  3        Helbing, Mathias                  1968                             0.0
001  1        Funke, Christian                  1748                             0.0
001  5        Heilmann, Matthias                1683                             0.0
001  2        Marks, Udo                        1640                             0.0
001  4        Beulshausen, Ralf                 1625                             0.0
001  6        Rudolph, Werner                   1466                             0.0
001  8        Göring, Joachim, Dr.              1030                             0.0
001  9        Klose, Benjamin                   1013                             0.0
001  7        Hempel, Bernd                     992                              0.0

Udo Marks (2) should be absent now. But the pairing returns:


[marks_paired.zip](https://github.com/BieremaBoyzProgramming/bbpPairings/files/15029320/marks_paired.zip)

**Comment by C1977** [comment]
Thanks, it works with 0000-Z
