### ISSUE TITLE
Suboptimal exchange in remainder

### ISSUE THREAD

**Issue by jbierema** [BieremaBoyzProgramming/bbpPairings#7]
Someone emailed me alerting me that the pairing of the last round in this file is incorrect. Player 42 should be paired in his own bracket, and player 45 should float.
[suboptimalExchangeInRemainder.txt](https://github.com/BieremaBoyzProgramming/bbpPairings/files/4467566/suboptimalExchangeInRemainder.txt)

**Comment by B-Esmaili** [comment]
if it is fixed why you keep it open?

**Comment by jbierema** [comment]
Hi, @B-Esmaili. It is fixed in the `develop` branch, but we haven't yet issued a new release with the fix.
