### ISSUE TITLE
How to build from source in ubuntu?

### ISSUE THREAD

**Issue by B-Esmaili** [BieremaBoyzProgramming/bbpPairings#8]
Thanks for sharing source.
How can i build from source in ubuntu?

**Comment by CheckMatt** [comment]
Hi,
The repository comes with a Makefile, which gives you the possibility to compile bbpPairings with
`make`.

**Comment by B-Esmaili** [comment]
I tried to compile but faced with following error :


![Capture](https://user-images.githubusercontent.com/9152515/82876047-6ab89000-9f4d-11ea-9d03-c2d15b1e0f4c.PNG)

i tried in `ubuntu` , `windows` and finally in `gitpod` but it gives same error.

**Comment by Methuselah96** [comment]
Have you tried running `make` instead of `g++ main.cpp`?

**Comment by B-Esmaili** [comment]
I have no idea hot make works.would you give me some hints?
